function [ S ] = lfsr_test( L, K, I, N, powtable, fsize )
%LFSR_TEST Calculates first N elements of sequence generated by LFSR

    %Initialize LFSR
    reg = I(1:L);
    for i=1:N
        %Calculate new S
        newS = 0;
        for j=1:L
            newS = bitxor(newS, gf_mul(K(j), reg(L - j + 1), powtable, fsize));
        end
        fprintf('S%d = %d\n', i, reg(1));
        %Shift
        reg = [reg(2:L) newS];
    end
end

